name: mitopup
description: Recharge the cell phone of your loved ones quickly, safely and easily.
publish_to: "none"

version: 1.0.0+1

# Environment
environment:
  sdk: ">=3.0.5 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  google_fonts: ^5.1.0
  file_picker: ^5.5.0
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  hexcolor: ^3.0.1
  http_parser: ^4.0.2
  im_stepper: ^1.0.1+1
  shared_preferences: ^2.2.1
  go_router: ^10.1.2
  intl: ^0.18.1
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  dio: ^5.3.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# Assets
flutter:
  uses-material-design: true
  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
    - assets/langs/
    - .env

# Internationalization
flutter_intl:
  enabled: true
  main_locale: es
  class_name: Literals
